### ISSUE TITLE
You lot are what is wrong with tech

### ISSUE THREAD

**Issue by philsturgeon** [The-Feminist-Software-Foundation/ToleranUX#1]
Give it a rest. Nobody is impressed.

**Comment by The-Feminist-Software-Foundation** [comment]
Feminism doesn't seek to impress.

Feminism seeks to improve.

You may disagree but that only proves you to be a bigot person.  And to be frank, you lot are what is wrong with tech — perpetuating the toxic and patriarchal meritocracy of FLOSS code.

**Comment by bithavoc** [comment]
:+1:

**Comment by jonathas** [comment]
Is this a joke?

**Comment by marcosgdf** [comment]
:+1:

**Comment by buritica** [comment]
![](https://pbs.twimg.com/media/B7fcaM8CMAA0DpI.jpg)
