### ISSUE TITLE
branch is called "master"

### ISSUE THREAD

**Issue by ChaimShekelberg** [The-Feminist-Software-Foundation/ToleranUX#3]
As a Jewish decendant, the term "master" is very triggering as my people were slaves to the Egyptian oppressors thousands of years ago before our plight to the promised land. Is there any way you can change this? Thank you

**Comment by ChaimShekelberg** [comment]
Please respond.

**Comment by tedstein** [comment]
I also wonder about the words "submit" and "submissions" -- why must we "submit" our code to this project? Submission isn't empowering at all.

I would much prefer to "permit" my code. Thank you.

**Comment by rektm8** [comment]
:heart_decoration:

**Comment by ChaimShekelberg** [comment]
Please fix this issue very quickly, I'm shaking at the thought of being triggered again by using ToleranUX. This is never going to be a safe space for oppressed minorities if we don't address this issue.
Shalom

**Comment by The-Feminist-Software-Foundation** [comment]
Branch `mistress` created and is now the default branch.

The `master` branch is obsolete and left ~~for backwards compatibility~~ to rot.
